project:
  type: website
  output-dir: docs

website:
  title: "Yingzhi Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
      - contact.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

